// <auto-generated />
namespace AuthLogin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initRegi1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initRegi1));
        
        string IMigrationMetadata.Id
        {
            get { return "202105110607548_initRegi1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
